//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ChiTietHDN
{
    public string MaHDN { get; set; }
    public string MaSP { get; set; }
    public string MaKH { get; set; }
    public Nullable<int> GiaNhap { get; set; }
    public Nullable<System.DateTime> NgayNhap { get; set; }
    public Nullable<int> SoLuongNhap { get; set; }
    public Nullable<int> TongTienNhap { get; set; }

    public virtual HoaDonNhap HoaDonNhap { get; set; }
}

public partial class ChiTietHDX
{
    public string MaHDX { get; set; }
    public string MaSP { get; set; }
    public string MaKH { get; set; }
    public Nullable<int> GiaXuat { get; set; }
    public Nullable<System.DateTime> NgayXuat { get; set; }
    public Nullable<int> SoLuongXuat { get; set; }
    public Nullable<int> TongTienXuat { get; set; }

    public virtual HoaDonXuat HoaDonXuat { get; set; }
}

public partial class GioHang
{
    public string MaGH { get; set; }
    public string MaKH { get; set; }
    public string MaSP { get; set; }
    public Nullable<int> SoLuong { get; set; }
    public Nullable<int> TongTien { get; set; }

    public virtual KhachHang KhachHang { get; set; }
    public virtual SanPham SanPham { get; set; }
}

public partial class HoaDonNhap
{
    public HoaDonNhap()
    {
        this.ChiTietHDNs = new HashSet<ChiTietHDN>();
    }

    public string MaHDN { get; set; }
    public string MaNCC { get; set; }
    public string MaNV { get; set; }
    public Nullable<System.DateTime> NgayNhap { get; set; }
    public Nullable<int> SoLuongNhap { get; set; }
    public Nullable<int> TongTienNhap { get; set; }

    public virtual ICollection<ChiTietHDN> ChiTietHDNs { get; set; }
    public virtual NhaCungCap NhaCungCap { get; set; }
    public virtual NhanVien NhanVien { get; set; }
}

public partial class HoaDonXuat
{
    public HoaDonXuat()
    {
        this.ChiTietHDXes = new HashSet<ChiTietHDX>();
    }

    public string MaHDX { get; set; }
    public string MaKH { get; set; }
    public string MaNV { get; set; }
    public Nullable<System.DateTime> NgayXuat { get; set; }
    public string DiaChiKH { get; set; }
    public Nullable<int> SoLuongXuat { get; set; }
    public Nullable<int> TongTienXuat { get; set; }

    public virtual ICollection<ChiTietHDX> ChiTietHDXes { get; set; }
    public virtual KhachHang KhachHang { get; set; }
    public virtual NhanVien NhanVien { get; set; }
}

public partial class KhachHang
{
    public KhachHang()
    {
        this.GioHangs = new HashSet<GioHang>();
        this.HoaDonXuats = new HashSet<HoaDonXuat>();
    }

    public string MaKH { get; set; }
    public string TenKH { get; set; }
    public string SdtKH { get; set; }
    public string DiaChiKH { get; set; }

    public virtual ICollection<GioHang> GioHangs { get; set; }
    public virtual ICollection<HoaDonXuat> HoaDonXuats { get; set; }
}

public partial class LoaiSP
{
    public LoaiSP()
    {
        this.SanPhams = new HashSet<SanPham>();
    }

    public string MaLoai { get; set; }
    public string TenLoai { get; set; }

    public virtual ICollection<SanPham> SanPhams { get; set; }
}

public partial class NhaCungCap
{
    public NhaCungCap()
    {
        this.HoaDonNhaps = new HashSet<HoaDonNhap>();
        this.SanPhams = new HashSet<SanPham>();
    }

    public string MaNCC { get; set; }
    public string TenNCC { get; set; }
    public string SdtNCC { get; set; }
    public string EmailNCC { get; set; }
    public string DiaChiNCC { get; set; }

    public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
    public virtual ICollection<SanPham> SanPhams { get; set; }
}

public partial class NhanVien
{
    public NhanVien()
    {
        this.HoaDonNhaps = new HashSet<HoaDonNhap>();
        this.HoaDonXuats = new HashSet<HoaDonXuat>();
    }

    public string MaNV { get; set; }
    public string TenNV { get; set; }
    public string GioiTinhNV { get; set; }
    public string SdtNV { get; set; }
    public string EmailNV { get; set; }
    public Nullable<int> CMTNV { get; set; }
    public string DiaChiNV { get; set; }
    public string ChuVuNV { get; set; }

    public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
    public virtual ICollection<HoaDonXuat> HoaDonXuats { get; set; }
}

public partial class SanPham
{
    public SanPham()
    {
        this.GioHangs = new HashSet<GioHang>();
    }

    public string MaSP { get; set; }
    public string TenSP { get; set; }
    public string MaLoai { get; set; }
    public string MaNCC { get; set; }
    public string HinhAnh { get; set; }
    public string ChucNang { get; set; }
    public Nullable<int> GiaBan { get; set; }
    public Nullable<int> GiaNhap { get; set; }

    public virtual ICollection<GioHang> GioHangs { get; set; }
    public virtual LoaiSP LoaiSP { get; set; }
    public virtual NhaCungCap NhaCungCap { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
