//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MyPham_ShopEntities1 : DbContext
{
    public MyPham_ShopEntities1()
        : base("name=MyPham_ShopEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ChiTietHDN> ChiTietHDNs { get; set; }
    public DbSet<ChiTietHDX> ChiTietHDXes { get; set; }
    public DbSet<GioHang> GioHangs { get; set; }
    public DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
    public DbSet<HoaDonXuat> HoaDonXuats { get; set; }
    public DbSet<KhachHang> KhachHangs { get; set; }
    public DbSet<LoaiSP> LoaiSPs { get; set; }
    public DbSet<NhaCungCap> NhaCungCaps { get; set; }
    public DbSet<NhanVien> NhanViens { get; set; }
    public DbSet<SanPham> SanPhams { get; set; }
    public DbSet<sysdiagram> sysdiagrams { get; set; }
}
